-- Insert roadmap skill nodes from D:/RoadmapDataTemplate.csv
-- Run this in PostgreSQL/Supabase SQL editor.
BEGIN;

CREATE TEMP TABLE roadmap_skill_node_seed (
    row_no INT PRIMARY KEY,
    node_id UUID NOT NULL DEFAULT gen_random_uuid(),
    career_name VARCHAR(255) NOT NULL,
    subtree_name VARCHAR(255),
    connect_to_name VARCHAR(255),
    child_node_of_name VARCHAR(255),
    node_name VARCHAR(255) NOT NULL,
    level INT,
    description TEXT,
    resource JSONB
) ON COMMIT DROP;

INSERT INTO roadmap_skill_node_seed (row_no, career_name, subtree_name, connect_to_name, child_node_of_name, node_name, level, description, resource) VALUES
    (1, 'Frontend', NULL, NULL, NULL, 'Internet', 1, 'The Internet is a global network of interconnected computers using TCP/IP protocols, connecting billions of devices worldwide. Revolutionized communication, commerce, education, and entertainment. Enables web browsing, streaming, and diverse applications while presenting privacy and security challenges.', '{"links": ["https://roadmap.sh/guides/what-is-internet", "https://en.wikipedia.org/wiki/Internet"]}'::jsonb),
    (2, 'Frontend', NULL, NULL, 'Internet', 'How does the internet work?', NULL, 'The internet is a global network connecting computers and devices for information sharing. Enables browsing, email, streaming, and communication through interconnected systems. Acts as worldwide infrastructure facilitating access to online resources and services.', '{"links": ["https://roadmap.sh/guides/what-is-internet", "https://cs.fyi/guide/how-does-internet-work", "https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_does_the_Internet_work"]}'::jsonb),
    (3, 'Frontend', NULL, NULL, 'Internet', 'What is HTTP?', NULL, 'HTTP (Hypertext Transfer Protocol) enables browser-server communication through requests and responses. Stateless protocol using methods like GET and POST. HTTPS provides encrypted security. Newer versions (HTTP/2, HTTP/3) offer improved performance. Fundamental for web development understanding.', '{"links": ["https://cs.fyi/guide/http-in-depth", "https://www.cloudflare.com/en-gb/learning/ddos/glossary/hypertext-transfer-protocol-http/", "https://howhttps.works"]}'::jsonb),
    (4, 'Frontend', NULL, NULL, 'Internet', 'What is Domain Name?', NULL, 'Domain names are human-friendly web addresses (e.g., [google.com](http://google.com)) substituting numerical IP addresses. Comprise second-level ("google") and top-level (".com") domains. Registered through registrars, essential for branding and online presence. DNS translates names to IP addresses for accessibility.', '{"links": ["http://google.com", "https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name", "https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name/"]}'::jsonb),
    (5, 'Frontend', NULL, NULL, 'Internet', 'What is hosting?', NULL, 'Web hosting stores website files on servers, making sites accessible online. Types include shared (multiple sites per server) and dedicated (exclusive server) hosting. Providers offer additional services like email, domains, and security certificates. Critical for website performance and accessibility.', '{"links": ["https://www.namecheap.com/hosting/what-is-web-hosting-definition/", "https://www.youtube.com/watch?v=AXVZYzw8geg", "https://www.youtube.com/watch?v=Kx_1NYYJS7Q"]}'::jsonb),
    (6, 'Frontend', NULL, NULL, 'Internet', 'DNS and how it works?', NULL, 'DNS (Domain Name System) translates human-readable domain names into IP addresses through a global, decentralized server network. Enables easy internet navigation by converting names like [www.example.com](http://www.example.com) to numeric addresses browsers can connect to.', '{"links": ["http://www.example.com", "https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/", "https://messwithdns.net/"]}'::jsonb),
    (7, 'Frontend', NULL, NULL, 'Internet', 'Browsers and how they work?', NULL, 'Web browsers request and display websites by interpreting HTML, CSS, and JavaScript. Use rendering engines (Blink, Gecko) for display and JavaScript engines (V8) for code execution. Handle security, bookmarks, history, and user interactions for web navigation.', '{"links": ["https://www.ramotion.com/blog/what-is-web-browser/", "https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work", "https://www.youtube.com/watch?v=5rLFYtXHo9s"]}'::jsonb),
    (8, 'Frontend', NULL, NULL, NULL, 'HTML', 2, 'HTML (Hypertext Markup Language) is the standard for creating web pages, structuring content with elements and attributes. Browsers interpret HTML tags to render pages. HTML5, the current standard, adds semantic elements, multimedia support, and form controls. It works with CSS for styling and JavaScript for interactivity, forming web development''s foundation.', '{"links": ["https://roadmap.sh/html", "https://www.freecodecamp.org/learn/2022/responsive-web-design/", "https://youtu.be/mJgBOIoGihA"]}'::jsonb),
    (9, 'Frontend', NULL, NULL, NULL, 'CSS', 3, 'CSS (Cascading Style Sheets) styles HTML documents, controlling layout, colors, and fonts. Separates design from content using selectors to target elements. Features responsive design with media queries, cascade rules, inheritance, and specificity. Modern CSS includes Flexbox, Grid, animations, and transitions.', '{"links": ["https://roadmap.sh/css", "https://www.freecodecamp.org/learn/2022/responsive-web-design/", "https://web.dev/learn/css/"]}'::jsonb),
    (10, 'Frontend', NULL, NULL, NULL, 'JavaScript', 4, 'JavaScript is a versatile programming language that makes websites interactive. Runs in browsers, servers (Node.js), and desktop applications. Features dynamic typing, event-driven programming, and constant evolution. Essential for modern web development across frontend and backend.', '{"links": ["https://roadmap.sh/javascript", "https://javascript.info/", "https://javascript30.com/"]}'::jsonb),
    (11, 'Frontend', NULL, NULL, NULL, 'Version Control', 5, 'Version Control Systems (VCS) like Git track code changes and enable developer collaboration through modification history. Features include branching, merging, reverting, remote repositories, pull requests, and code reviews. Essential for modern software development productivity, quality, and teamwork.', '{"links": ["https://roadmap.sh/git-github", "https://www.youtube.com/watch?v=IeXhYROClZk", "https://www.atlassian.com/git/tutorials/what-is-version-control"]}'::jsonb),
    (12, 'Frontend', NULL, NULL, 'Version Control', 'Git', NULL, 'Git is a distributed version control system tracking code changes and enabling collaborative development. Features branching, merging, and complete project history. Allows offline work with local repositories. Fast, flexible, and the most popular VCS for software projects.', '{"links": ["https://roadmap.sh/git-github", "https://thenewstack.io/tutorial-git-for-absolutely-everyone/", "https://www.youtube.com/watch?v=SWYqp7iY_Tc"]}'::jsonb),
    (13, 'Frontend', NULL, NULL, NULL, 'VCS Hosting', 6, 'Repository hosting services (GitHub, GitLab, Bitbucket) provide platforms for storing, managing, and collaborating on software projects using Git version control. Facilitate teamwork, code sharing, project tracking, and distributed software development workflows.', '{"links": ["https://roadmap.sh/git-github", "https://github.com", "https://about.gitlab.com"]}'::jsonb),
    (14, 'Frontend', NULL, NULL, 'VCS Hosting', 'GitHub', NULL, 'GitHub is the leading Git repository hosting platform for open-source and private projects. Owned by Microsoft since 2018, it''s essential for modern software development, project showcasing, and open-source contributions. Central hub for developer collaboration and code sharing.', '{"links": ["https://roadmap.sh/git-github", "https://docs.github.com/en/get-started/quickstart/hello-world", "https://skills.github.com/"]}'::jsonb),
    (15, 'Frontend', NULL, NULL, 'VCS Hosting', 'GitLab', NULL, 'GitLab is a comprehensive DevOps platform offering integrated development tools including Git hosting, CI/CD, issue tracking, and deployment. Available as cloud service or self-hosted solution. Popular with enterprises seeking unified development workflows and built-in automation capabilities.', '{"links": ["https://gitlab.com/", "https://docs.gitlab.com/", "https://thenewstack.io/development-connect-git-to-gitlab-for-small-projects/"]}'::jsonb),
    (16, 'Frontend', NULL, NULL, NULL, 'Package Managers', 7, 'Package managers automate software package installation, updates, and dependency management. Examples include npm (JavaScript), pip (Python), and yarn. Enable code sharing, reuse, and consistent project setups. Essential for modern development workflows and team collaboration.', '{"links": ["https://pnpm.io/", "https://yarnpkg.com/en/docs/getting-started", "https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/"]}'::jsonb),
    (17, 'Frontend', NULL, NULL, 'Package Managers', 'Bun', NULL, 'Bun is a JavaScript runtime, bundler, transpiler, and package manager, all-in-one. It''s designed to be a faster, more efficient alternative to Node.js and npm, aiming to improve performance and developer experience through its speed and comprehensive toolset. Bun uses JavaScriptCore, Apple''s JavaScript engine, which is known for its performance.', '{"links": ["https://bun.com/", "https://bun.com/docs", "https://github.com/oven-sh/bun"]}'::jsonb),
    (18, 'Frontend', NULL, NULL, 'Package Managers', 'npm', NULL, 'npm (Node Package Manager) is the primary JavaScript package manager for finding, sharing, and managing code dependencies. Uses package.json to track project requirements and enables consistent builds across environments. Remains the most popular choice despite alternatives like Yarn and pnpm.', '{"links": ["https://www.npmjs.com/", "https://docs.npmjs.com/", "https://github.com/workshopper/how-to-npm"]}'::jsonb),
    (19, 'Frontend', NULL, NULL, 'Package Managers', 'pnpm', NULL, 'pnpm (performant npm) is a fast, disk-efficient JavaScript package manager using global storage with symlinks. Saves disk space, ensures strict package.json compliance, supports monorepos, and provides better security through dependency isolation. Growing popularity for speed and efficiency.', '{"links": ["https://pnpm.io", "https://blog.bitsrc.io/pnpm-javascript-package-manager-4b5abd59dc9", "https://www.youtube.com/watch?v=MvbReZDSKHI"]}'::jsonb),
    (20, 'Frontend', NULL, NULL, 'Package Managers', 'yarn', NULL, 'Yarn is Facebook''s JavaScript package manager offering fast, reliable, secure alternative to npm. Features lockfile consistency, parallel installations, offline mode, and checksum verification. Yarn Berry with Plug''n''Play improves performance for large projects.', '{"links": ["https://yarnpkg.com/en/docs/getting-started", "https://www.youtube.com/watch?v=g9_6KmiBISk", "https://app.daily.dev/tags/yarn?ref=roadmapsh"]}'::jsonb),
    (21, 'Frontend', NULL, NULL, NULL, 'CSS Frameworks', 8, 'Modern CSS creates responsive designs using media queries, flexible typography, CSS-in-JS, and frameworks like Tailwind. Features CSS Logical Properties for internationalization and CSS Houdini for custom styling. Goals: performance, maintainability, and accessible designs across all devices.', '{"links": ["https://moderncss.dev/", "https://css-tricks.com/modern-css/", "https://app.daily.dev/tags/css?ref=roadmapsh"]}'::jsonb),
    (22, 'Frontend', NULL, NULL, 'CSS Frameworks', 'Tailwind', NULL, 'Tailwind CSS is a utility-first CSS framework providing small, composable classes for rapid custom design development. Features mobile-first approach, automatic unused style removal (purging), and flexible customization. Enables quick responsive design prototyping without writing custom CSS.', '{"links": ["https://www.youtube.com/watch?v=lCxcTsOHrjo", "https://tailwindcss.com", "https://play.tailwindcss.com"]}'::jsonb),
    (23, 'Frontend', NULL, NULL, NULL, 'Learn a Framework', 9, 'Web frameworks are development toolkits providing libraries, structure, rules, and tools for building applications. Different frameworks offer varying features based on project needs. Popular examples include React, Angular, and Vue, each with unique strengths and capabilities.', '{"links": ["https://www.youtube.com/watch?v=466U-2D86bc", "https://www.youtube.com/watch?v=cuHDQhDhvPE"]}'::jsonb),
    (24, 'Frontend', NULL, NULL, 'Learn a Framework', 'React', NULL, 'React is a JavaScript tool from Facebook for building UIs, especially for single-page apps. It lets you create reusable UI parts that update when data changes. React uses a virtual DOM for speed and has a one-way data flow. This component style makes code neat and reusable. React also works with tools like Redux for data management and React Native for mobile apps. It''s popular because it''s clear, fast, and has a big community.', '{"links": ["https://roadmap.sh/react", "https://www.youtube.com/watch?v=Bvwq_S0n2pk", "https://react.dev"]}'::jsonb),
    (25, 'Frontend', NULL, NULL, 'Learn a Framework', 'Vue.js', NULL, 'Vue.js is a JavaScript framework for building website interfaces. It''s easy to start with and can be added to projects bit by bit. Vue uses templates and a virtual DOM (a lightweight copy of the real page) to show things on screen efficiently. It has a system of reusable components, making code organized. While Vue mainly handles what users see, it works well with other tools for things like managing data or page navigation. It''s known for being easy to learn, flexible, and fast, making it popular for all kinds of projects.', '{"links": ["https://roadmap.sh/vue", "https://vuejs.org/", "https://www.youtube.com/watch?v=VeNfHj6MhgA"]}'::jsonb),
    (26, 'Frontend', NULL, NULL, 'Learn a Framework', 'Angular', NULL, 'Angular is Google''s TypeScript framework for building single-page applications (SPAs). Features reusable components, two-way data binding, dependency injection, and robust template system. Includes testing tools, routing, and state management. Ideal for large, complex enterprise applications.', '{"links": ["https://roadmap.sh/angular", "https://angular.dev/tutorials/learn-angular", "https://www.youtube.com/watch?v=3qBXWUpoPHo"]}'::jsonb),
    (27, 'Frontend', NULL, NULL, 'Learn a Framework', 'Svelte', NULL, 'Svelte is a JavaScript tool for building UIs. Unlike others, Svelte does its main work during build time, not in the browser. It turns your code into small, fast, plain JavaScript. Svelte uses components and has a simple syntax, so you write less code. It includes features for managing data, styling, and animations. Because Svelte doesn''t use a virtual DOM, pages load and update quickly. It''s liked for its simplicity and speed.', '{"links": ["https://www.youtube.com/playlist?list=PL4cUxeGkcC9hlbrVO_2QFVqVPhlZmz7tO", "https://svelte.dev/", "https://thenewstack.io/svelte-and-the-future-of-front-end-development/"]}'::jsonb),
    (28, 'Frontend', NULL, NULL, 'Learn a Framework', 'Solid JS', NULL, 'SolidJS is a JavaScript tool for building website interfaces that is known for being very fast and efficient. It updates only the parts of the page that change, which makes it perform well. SolidJS doesn''t use a virtual DOM; instead, it directly changes the real DOM. Its syntax is like React, so many developers find it familiar. It supports JSX, has built-in ways to manage data, and is small in size. SolidJS is getting popular for its speed, simplicity, and smart way of handling updates.', '{"links": ["https://www.solidjs.com/", "https://www.solidjs.com/tutorial/introduction_basics", "https://www.youtube.com/watch?v=hw3Bx5vxKl0"]}'::jsonb),
    (29, 'Frontend', 'AI in Development', 'Learn a Framework', NULL, 'Learn the Basics', 1, 'Generative AI uses algorithms to create new content, like code or designs, based on the data it''s trained on. This means it can help frontend developers by automatically generating things like UI elements, suggesting code snippets, or even creating entire webpage layouts based on specific requirements and examples. Essentially, it''s a tool that can automate repetitive tasks and inspire new ideas in the frontend development workflow.', '{"links": ["https://www.ibm.com/think/topics/ai-in-software-development", "https://github.com/resources/articles/ai-in-software-development", "https://blog.logrocket.com/frontend-ai-tools-for-developers/"]}'::jsonb),
    (30, 'Frontend', NULL, NULL, 'Learn the Basics', 'How LLMs work', NULL, 'LLMs, or Large Language Models, are advanced AI models trained on vast datasets to understand and generate human-like text. They can perform a wide range of natural language processing tasks, such as text generation, translation, summarization, and question answering. LLMs function as sophisticated prediction engines that process text sequentially, predicting the next token based on relationships between previous tokens and patterns from training data. They don''t predict single tokens directly but generate probability distributions over possible next tokens, which are then sampled using parameters like temperature and top-K. The model repeatedly adds predicted tokens to the sequence, building responses iteratively. This token-by-token prediction process, combined with massive training datasets, enables LLMs to generate coherent, contextually relevant text across diverse applications and domains.', '{"links": ["https://roadmap.sh/ai-engineer", "https://www.cloudflare.com/en-gb/learning/ai/what-is-large-language-model/", "https://leerob.com/ai"]}'::jsonb),
    (31, 'Frontend', NULL, NULL, 'Learn the Basics', 'AI vs Traditional Coding', NULL, 'Traditional software development relies on developers explicitly writing code to instruct computers on how to perform tasks. This involves defining every step and logic manually. AI-assisted coding, however, leverages machine learning models trained on vast amounts of code to automate parts of the development process. Instead of writing all the code from scratch, developers can use AI to generate code snippets, suggest improvements, and even debug errors, potentially leading to faster development cycles and reduced human error.', '{"links": ["https://www.mckinsey.com/industries/technology-media-and-telecommunications/our-insights/unlocking-the-value-of-ai-in-software-development", "https://www.ibm.com/think/topics/vibe-coding", "https://www.anthropic.com/research/how-ai-is-transforming-work-at-anthropic"]}'::jsonb),
    (32, 'Frontend', NULL, NULL, 'Learn the Basics', 'Applications', NULL, 'AI is increasingly being used to automate tasks, improve user interfaces, and enhance the overall development process in frontend. It can help with code generation, intelligent suggestions, automated testing, and creating personalized user experiences through features like dynamic content and adaptive layouts. This integration aims to make development faster, more efficient, and more user-centric.', '{"links": ["https://www.ibm.com/think/topics/ai-in-software-development", "https://appfire.com/resources/blog/ai-in-software-development", "https://aalapdavjekar.medium.com/ai-assisted-software-development-a-comprehensive-guide-with-practical-prompts-part-1-3-989a529908e0"]}'::jsonb),
    (33, 'Frontend', NULL, NULL, 'Learn the Basics', 'Code Reviews', NULL, 'AI-powered code reviews leverage machine learning models to analyze source code and identify potential issues, such as bugs, security vulnerabilities, code style violations, and performance bottlenecks. These tools can automate parts of the code review process, freeing up developers to focus on more complex problems and improving the overall quality and maintainability of the codebase.', '{"links": ["https://code.claude.com/docs/en/common-workflows", "https://github.com/resources/articles/ai-code-reviews", "https://www.startearly.ai/post/ai-code-review-how-to-make-it-work-for-you"]}'::jsonb),
    (34, 'Frontend', NULL, NULL, 'Learn the Basics', 'Refactoring', NULL, 'Refactoring, in the context of software development, is the process of restructuring existing computer code?changing its internal structure?without changing its external behavior. AI tools can assist in this process by analyzing code for potential improvements in readability, performance, and maintainability. They can automatically suggest or even implement changes like simplifying complex logic, removing redundant code, and improving code style consistency, ultimately leading to a cleaner and more efficient codebase.', '{"links": ["https://www.ibm.com/think/topics/ai-code-refactoring", "https://graphite.com/guides/what-is-ai-code-refactoring", "https://www.youtube.com/watch?v=B7Yt-WmlW2I"]}'::jsonb),
    (35, 'Frontend', NULL, NULL, 'Learn the Basics', 'Docs Generation', NULL, 'AI-powered documentation generation leverages machine learning models to automatically create and maintain software documentation. These tools can analyze code, comments, and other project artifacts to produce API references, tutorials, and other types of documentation, reducing the manual effort required and ensuring accuracy and consistency. This helps developers by freeing them from manual tasks and ensuring that their APIs are well documented.', '{"links": ["https://www.ibm.com/think/insights/ai-code-documentation-benefits-top-tips", "https://overcast.blog/ai-code-documentation-generators-a-guide-b6cd72cd0ec4", "https://medium.com/@fra.bernhardt/automate-your-documentation-with-claude-code-github-actions-a-step-by-step-guide-2be2d315ed45"]}'::jsonb),
    (36, 'Frontend', NULL, NULL, NULL, 'AI Assisted Coding', 10, 'AI-assisted coding involves using artificial intelligence tools to help developers write code more efficiently and effectively. These tools can provide real-time suggestions, automate repetitive tasks, identify potential errors, and even generate code snippets based on natural language descriptions, ultimately speeding up development and improving code quality.', '{"links": ["https://www.hkdca.com/wp-content/uploads/2025/06/ai-assisted-programming-oreilly.pdf", "https://www.freecodecamp.org/news/how-to-become-an-expert-in-ai-assisted-coding-a-handbook-for-developers/", "https://statistician-in-stilettos.medium.com/best-practices-i-learned-for-ai-assisted-coding-70ff7359d403"]}'::jsonb),
    (37, 'Frontend', NULL, NULL, 'AI Assisted Coding', 'Cursor', NULL, 'Cursor is an AI-powered code editor designed to enhance developer productivity. It leverages large language models to offer features like code completion, generation, and refactoring suggestions. By understanding code context, Cursor aims to automate repetitive tasks and provide intelligent assistance throughout the development process.', '{"links": ["https://cursor.com/", "https://cursor.com/docs", "https://cursor.com/learn"]}'::jsonb),
    (38, 'Frontend', NULL, NULL, 'AI Assisted Coding', 'Antigravity', NULL, 'Antigravity is an AI-powered code completion tool designed to enhance developer productivity. Created by Google, it learns from your coding style and project context to provide intelligent suggestions, autocompletions, and code generation snippets directly within your integrated development environment (IDE). This allows developers to write code faster and more efficiently, reducing errors and streamlining the development process.', '{"links": ["https://antigravity.google/", "https://codelabs.developers.google.com/getting-started-google-antigravity#0", "https://thenewstack.io/hands-on-with-antigravity-googles-newest-ai-coding-experiment/"]}'::jsonb),
    (39, 'Frontend', NULL, NULL, 'AI Assisted Coding', 'Claude Code', NULL, 'Claude Code is a family of large language models designed for code generation and understanding. It excels at tasks like code completion, bug finding, documentation, and even translating code between different programming languages. Essentially, it''s a tool that helps developers write, understand, and maintain code more efficiently by leveraging artificial intelligence.', '{"links": ["https://roadmap.sh/claude-code", "https://code.claude.com/docs/en/overview", "https://www.youtube.com/watch?v=AJpK3YTTKZ4"]}'::jsonb),
    (40, 'Frontend', NULL, NULL, 'AI Assisted Coding', 'Copilot', NULL, 'GitHub Copilot is an AI-powered code-completion tool that helps developers write code faster and with fewer errors. It uses a combination of machine learning algorithms and access to GitHub''s vast repository of open-source code to provide context-aware suggestions for coding tasks. Copilot can generate entire functions, methods, or even entire classes based on the context of the code being written. This feature aims to reduce the time spent on coding by providing immediate and relevant suggestions, allowing developers to focus more on high-level design and problem-solving.', '{"links": ["https://docs.github.com/en/copilot/quickstart", "https://docs.github.com/en/copilot/tutorials", "https://www.tutorialspoint.com/github-copilot/index.htm"]}'::jsonb),
    (41, 'Frontend', NULL, NULL, NULL, 'Prompting Techniques', 11, 'Prompt engineering is the process of crafting effective inputs (prompts) to guide AI models to generate desired outputs. It involves strategically designing prompts to optimize the model?s performance by providing clear instructions, context, and examples. Effective prompt engineering can improve the quality, relevance, and accuracy of responses, making it essential for applications like chatbots, content generation, and automated support. By refining prompts, developers can better control the model?s behavior, reduce ambiguity, and achieve more consistent results, enhancing the overall effectiveness of AI-driven systems.', '{"links": ["https://roadmap.sh/prompt-engineering", "https://learnprompting.org/courses/intro-to-prompt-engineering", "https://www.datacamp.com/blog/what-is-prompt-engineering-the-future-of-ai-communication"]}'::jsonb),
    (42, 'Frontend', NULL, NULL, NULL, 'Agents', 12, 'AI agents are autonomous programs designed to help developers write code more efficiently. These agents can automate repetitive tasks, suggest code completions, identify errors, and even generate entire code blocks based on natural language descriptions or existing code patterns. They leverage machine learning models to understand code syntax, semantics, and context, enabling them to provide intelligent and relevant assistance throughout the software development lifecycle.', '{"links": ["https://roadmap.sh/ai-agents", "https://www.ibm.com/think/topics/ai-agents", "https://www.geeky-gadgets.com/ai-agents-explained-for-beginners/"]}'::jsonb),
    (43, 'Frontend', NULL, NULL, NULL, 'MCP', 13, 'Model Context Protocol (MCP) is a rulebook that tells an AI agent how to pack background information before it sends a prompt to a language model. It lists what pieces go into the prompt?things like the system role, the user?s request, past memory, tool calls, or code snippets?and fixes their order. Clear tags mark each piece, so both humans and machines can see where one part ends and the next begins. Keeping the format steady cuts confusion, lets different tools work together, and makes it easier to test or swap models later. When agents follow MCP, the model gets a clean, complete prompt and can give better answers.', '{"links": ["https://www.deeplearning.ai/short-courses/mcp-build-rich-context-ai-apps-with-anthropic/", "https://modelcontextprotocol.io/introduction", "https://github.com/modelcontextprotocol/modelcontextprotocol"]}'::jsonb),
    (44, 'Frontend', NULL, NULL, NULL, 'Skills', 14, 'AI coding assistants can leverage "skills" ? pre-defined functions or tools exposed to the AI that allow it to perform specific actions. Instead of relying solely on their internal knowledge and large language models, these assistants can call upon these skills (like running tests, deploying code, or querying databases) when needed. This allows the AI to interact with the development environment and execute tasks directly, improving accuracy and efficiency, all while minimizing the context window required for each action.', '{"links": ["https://www.deeplearning.ai/short-courses/agent-skills-with-anthropic/", "https://medium.com/@richardhightower/agent-skills-the-universal-standard-transforming-how-ai-agents-work-fc7397406e2e", "https://thenewstack.io/ai-agents-or-skills-why-the-answer-is-both/"]}'::jsonb),
    (45, 'Frontend', NULL, NULL, NULL, 'Implementing AI', 15, 'Implementing AI in frontend development involves integrating artificial intelligence capabilities directly into user interfaces and workflows. This can range from simple tasks like intelligent form validation to complex features such as personalized content recommendations or AI-powered chatbots. Several major providers offer generative AI solutions that can be leveraged for frontend implementation, including Google with its AI platform, Antropic with its models like Claude, and OpenAI with its popular GPT series. These tools provide developers with the ability to incorporate AI functionalities to improve user experience and streamline development processes.', '{"links": ["https://www.aqedigital.com/blog/anthropic-vs-openai-vs-gemini/"]}'::jsonb),
    (46, 'Frontend', NULL, NULL, 'Implementing AI', 'Gemini', NULL, 'Gemini is a family of multimodal large language models (LLMs) developed by Google. These models are designed to handle and understand different types of data, including text, code, images, audio, and video. They are used to build AI-powered features by providing capabilities such as natural language understanding, content generation, and complex reasoning.', '{"links": ["https://gemini.google.com/", "https://workspace.google.com/solutions/ai/", "https://www.youtube.com/watch?v=_fuimO6ErKI"]}'::jsonb),
    (47, 'Frontend', NULL, NULL, 'Implementing AI', 'OpenAI', NULL, 'OpenAI provides a suite of artificial intelligence models and tools accessible through an API. These models can perform tasks like generating text, translating languages, writing different kinds of creative content, and answering your questions in an informative way. Developers can integrate these powerful AI capabilities into their applications by sending requests to OpenAI''s API endpoints and receiving responses.', '{"links": ["https://platform.openai.com/docs/overview", "https://platform.openai.com/docs/models", "https://academy.openai.com/"]}'::jsonb),
    (48, 'Frontend', NULL, NULL, 'Implementing AI', 'Anthropic', NULL, 'Anthropic is an AI safety and research company focused on developing reliable, interpretable, and steerable AI systems. They create AI models, like Claude, that are designed to be helpful, harmless, and honest, prioritizing safety through techniques like Constitutional AI, where the AI is guided by a set of principles during its training and operation. They can be integrated via APIs to add functionality to applications.', '{"links": ["https://www.anthropic.com/", "https://www.anthropic.com/learn", "https://claude.com/resources/tutorials"]}'::jsonb),
    (49, 'Frontend', NULL, NULL, NULL, 'Linters & Formatters', 16, 'Linters and formatters improve code quality by finding errors, bugs, and style issues (linters) and automatically fixing formatting like indentation and spacing (formatters). Ensure consistency, readability, and early error detection. Examples: ESLint, Prettier.', '{"links": ["https://www.testim.io/blog/what-is-a-linter-heres-a-definition-and-quick-start-guide/"]}'::jsonb),
    (50, 'Frontend', NULL, NULL, 'Linters & Formatters', 'Biome', NULL, 'Biome is a high-performance tool for web projects, designed to format and lint code. It aims to replace a suite of existing tools like Prettier, ESLint, and others, offering a unified solution for code quality and consistency. Biome supports languages like JavaScript, TypeScript, JSX, and JSON, helping developers maintain a clean and standardized codebase.', '{"links": ["https://biomejs.dev/", "https://github.com/biomejs/biome", "https://blog.openreplay.com/biome-toolchain-modern-frontend-projects/"]}'::jsonb),
    (51, 'Frontend', NULL, NULL, NULL, 'Module Bundlers', 17, 'Module bundlers combine multiple JavaScript files into optimized bundles for browsers. Handle dependencies, code transformation, and splitting for performance. Examples: Webpack, Rollup, Parcel. Enable modern JavaScript features, improve load times, and streamline development workflows.', '{"links": ["https://rollupjs.org/", "https://webpack.js.org/", "https://snipcart.com/blog/javascript-module-bundler"]}'::jsonb),
    (52, 'Frontend', NULL, NULL, 'Module Bundlers', 'Vite', NULL, 'Vite is a modern build tool using native ES modules for instant server starts and fast Hot Module Replacement. Supports Vue, React, Svelte with Rollup for production builds. Features CSS pre-processors and TypeScript integration. Enhances developer experience with faster development cycles.', '{"links": ["https://vite.dev", "https://vite.dev/guide/", "https://youtu.be/LQQ3CR2JTX8"]}'::jsonb),
    (53, 'Frontend', NULL, NULL, 'Linters & Formatters', 'Prettier', NULL, 'Prettier automatically formats code for consistency across JavaScript, TypeScript, CSS, and other languages. Enforces opinionated style rules, eliminating style debates and saving time. Integrates with editors and pre-commit hooks. Popular for maintaining uniform code appearance across teams.', '{"links": ["https://prettier.io", "https://prettier.io/docs/en/why-prettier.html", "https://www.youtube.com/watch?v=DqfQ4DPnRqI"]}'::jsonb),
    (54, 'Frontend', NULL, NULL, 'Linters & Formatters', 'ESLint', NULL, 'ESLint is a JavaScript linter checking code for problems, maintaining consistent style, and finding errors. Highly configurable with custom or preset rules. Supports modern JavaScript, JSX, TypeScript. Integrates with editors and build tools, offers automatic fixing for team consistency.', '{"links": ["https://eslint.org/", "https://2coffee.dev/en/articles/what-is-eslint-and-how-to-use-eslint-to-detect-fix-code-for-javascript-projects", "https://www.youtube.com/watch?v=qhuFviJn-es"]}'::jsonb),
    (55, 'Frontend', NULL, NULL, 'Module Bundlers', 'SWC', NULL, 'SWC (Speedy Web Compiler) is a Rust-based JavaScript/TypeScript compiler and bundler, much faster than Babel. Supports modern JavaScript features, JSX, and TypeScript compilation. Popular for large projects and as performance foundation for other build tools.', '{"links": ["https://swc.rs/", "https://swc.rs/docs/", "https://dev.to/somelink/why-swc-is-the-future-of-javascript-tooling"]}'::jsonb),
    (56, 'Frontend', NULL, NULL, 'Module Bundlers', 'Rollup', NULL, 'Rollup is a JavaScript bundler creating efficient bundles from ES modules. Excels at tree-shaking to remove unused code and supports multiple output formats. Produces smaller bundles than alternatives, ideal for libraries and modern JavaScript projects requiring optimization.', '{"links": ["https://rollupjs.org/", "https://www.youtube.com/watch?v=ICYLOZuFMz8", "https://app.daily.dev/tags/webdev?ref=roadmapsh"]}'::jsonb),
    (57, 'Frontend', NULL, NULL, 'Module Bundlers', 'Parcel', NULL, 'Parcel is a zero-configuration web app bundler handling JavaScript, CSS, HTML automatically. Features dependency resolution, code transformation, optimization, live reloading, code splitting, and tree-shaking by default. Known for simplicity and speed, ideal for rapid prototyping.', '{"links": ["https://parceljs.org/plugin-system/bundler/", "https://www.youtube.com/watch?v=R02ehdTzi3I", "https://app.daily.dev/tags/webdev?ref=roadmapsh"]}'::jsonb),
    (58, 'Frontend', NULL, NULL, 'Module Bundlers', 'esbuild', NULL, 'esbuild is an extremely fast JavaScript bundler and minifier written in Go. Handles modern JavaScript, TypeScript, and JSX with near-instant bundling. Simple API with excellent performance for development and as foundation for other tools. Trades some advanced features for speed.', '{"links": ["https://www.youtube.com/watch?v=KLdF1yu_bmI", "https://esbuild.github.io/", "https://www.youtube.com/watch?v=ZY8Vu8cbWF0"]}'::jsonb),
    (59, 'Frontend', NULL, NULL, 'Module Bundlers', 'Rolldown', NULL, 'Rolldown is a fast JavaScript bundler written in Rust, designed to be a drop-in replacement for Rollup. It takes your JavaScript and related assets (like CSS and images) and packages them into optimized bundles that can be efficiently loaded in a web browser. Rolldown aims to improve build performance and provide a smoother development experience compared to existing JavaScript bundlers.', '{"links": ["https://rolldown.rs/", "https://rolldown.rs/guide/getting-started", "https://github.com/rolldown/rolldown"]}'::jsonb),
    (60, 'Frontend', NULL, NULL, NULL, 'Auth Strategies', 18, 'Authentication strategies verify a user''s identity to grant access. Common methods include Basic Auth (username/password), Session-based (server remembers login), Token-based (like JWT, a secure digital key), OAuth (for third-party access like "Login with Google"), and SSO (Single Sign-On, one login for many apps). Knowing these helps choose the right security for your app.', '{"links": ["https://roadmap.sh/guides/basic-authentication", "https://roadmap.sh/guides/session-based-authentication-visually-explained", "https://roadmap.sh/guides/token-authentication"]}'::jsonb),
    (61, 'Frontend', NULL, NULL, NULL, 'Testing', 19, 'Testing verifies software functionality and quality through unit, integration, functional, UI/UX, performance, security, accessibility, and compatibility testing. Modern approaches use automated tools, CI/CD pipelines, TDD, and BDD methodologies. Early bug detection improves application reliability.', '{"links": ["https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing", "https://www.youtube.com/watch?v=l3qjQpYBR8c", "https://app.daily.dev/tags/testing?ref=roadmapsh"]}'::jsonb),
    (62, 'Frontend', NULL, NULL, 'Testing', 'Vitest', NULL, 'Vitest is a fast JavaScript/TypeScript testing framework optimized for Vite with Jest-compatible API. Features live test updates, snapshot testing, mocking, code coverage, parallel execution, and watch mode. Designed for Vite projects but works with any JavaScript project.', '{"links": ["https://vitest.dev/", "https://vitest.dev/guide/", "https://www.youtube.com/watch?v=snCLQmINqCU"]}'::jsonb),
    (63, 'Frontend', NULL, NULL, 'Testing', 'Jest', NULL, 'Jest is Facebook''s JavaScript testing framework for unit testing with auto mocking, code coverage, and snapshot testing. Works with React, Angular, Vue. Features parallel test execution, watch mode, and built-in assertion library. Top choice for JavaScript developers.', '{"links": ["https://jestjs.io/", "https://youtu.be/IPiUDhwnZxA?si=2_lE2bDo2fRuo2CU", "https://app.daily.dev/tags/jest?ref=roadmapsh"]}'::jsonb),
    (64, 'Frontend', NULL, NULL, 'Testing', 'Playwright', NULL, 'Playwright is Microsoft''s cross-browser automation testing framework supporting Chromium, Firefox, WebKit across platforms. Works with JavaScript, TypeScript, Python, .NET. Features auto-waiting, network control, mobile simulation. Excellent for modern web app testing with debugging tools.', '{"links": ["https://playwright.dev/", "https://thenewstack.io/playwright-a-time-saving-end-to-end-testing-framework/", "https://www.youtube.com/playlist?list=PLQ6Buerc008ed-F9OksF7ek37wR3y916p"]}'::jsonb),
    (65, 'Frontend', NULL, NULL, 'Testing', 'Cypress', NULL, 'Cypress is a JavaScript end-to-end testing framework running tests directly in browsers. Built on Mocha with excellent asynchronous testing support. Features time-travel debugging, automatic waiting, and real-time reloading. Supports BDD/TDD approaches for comprehensive web application testing.', '{"links": ["https://www.cypress.io/", "https://docs.cypress.io/", "https://www.youtube.com/watch?v=BQqzfHQkREo"]}'::jsonb),
    (66, 'Frontend', NULL, NULL, NULL, 'Web APIs', 20, 'Web APIs are interfaces provided by web browsers that allow JavaScript code to interact with the browser environment and the wider web. These APIs provide access to functionalities like manipulating the Document Object Model (DOM), handling user input, making network requests, managing browser history, and accessing device hardware like the camera or microphone. They essentially bridge the gap between JavaScript and the capabilities of the browser and the underlying operating system.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/API", "https://www.w3schools.com/js/js_api_intro.asp", "https://www.youtube.com/watch?v=_7rT-ixivWU"]}'::jsonb),
    (67, 'Frontend', NULL, NULL, NULL, 'Web Security', 21, 'Web security protects websites from cyber threats through HTTPS/TLS, XSS/SQL injection/CSRF prevention, CSP, secure authentication, input validation, and regular updates. Involves understanding OWASP Top Ten vulnerabilities, access controls, secure coding practices, and threat awareness for comprehensive protection.', '{"links": ["https://owasp.org/", "https://cheatsheetseries.owasp.org/cheatsheets/AJAX_Security_Cheat_Sheet.html", "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"]}'::jsonb),
    (68, 'Frontend', NULL, NULL, 'Web Security', 'OWASP Risks', NULL, 'OWASP (Open Web Application Security Project) identifies top web application security risks including injection attacks, broken authentication, data exposure, and vulnerable dependencies. Provides guidance on secure coding practices, regular security testing, and comprehensive protection strategies for web applications.', '{"links": ["https://owasp.org/", "https://cheatsheetseries.owasp.org/cheatsheets/AJAX_Security_Cheat_Sheet.html", "https://github.com/0xRadi/OWASP-Web-Checklist"]}'::jsonb),
    (69, 'Frontend', NULL, NULL, 'Web Security', 'HTTPS', NULL, 'HTTPS (Hypertext Transfer Protocol Secure) is HTTP''s encrypted version, securing data transmission between browsers and websites. Essential for protecting sensitive information like banking and email. Ensures privacy and security through data encryption for online communications.', '{"links": ["https://www.cloudflare.com/en-gb/learning/ssl/what-is-https/", "https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https", "https://web.dev/enable-https/"]}'::jsonb),
    (70, 'Frontend', NULL, NULL, 'Web Security', 'CORS', NULL, 'CORS (Cross-Origin Resource Sharing) controls web page access to resources from different domains through HTTP headers. Servers specify allowed origins while browsers send preflight requests for permission. Prevents unauthorized access while enabling legitimate cross-origin requests for modern multi-domain applications.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS", "https://rbika.com/blog/understanding-cors", "https://www.youtube.com/watch?v=PNtFSVU-YTI"]}'::jsonb),
    (71, 'Frontend', NULL, NULL, 'Web Security', 'CSP', NULL, 'Content Security Policy (CSP) prevents XSS and clickjacking attacks by specifying trusted content sources through HTTP headers. Website creators define safe sources for scripts, styles, images, and other resources. Limits malicious code execution and provides violation reporting for security monitoring.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP", "https://web.dev/csp/", "https://app.daily.dev/tags/security?ref=roadmapsh"]}'::jsonb),
    (72, 'Frontend', NULL, NULL, NULL, 'SSR', 22, 'Server-side rendering (SSR) generates complete HTML on the server before sending to browsers. Improves initial load times, SEO, and performance on slow devices. Frameworks: Next.js (React), Nuxt.js (Vue). Increases server load but enhances user experience.', '{"links": ["https://vuejs.org/guide/scaling-up/ssr.html", "https://www.youtube.com/watch?v=ObrSuDYMl1s", "https://www.youtube.com/watch?v=okvg3MRAPs0"]}'::jsonb),
    (73, 'Frontend', NULL, NULL, 'SSR', 'React', NULL, 'React is Facebook''s JavaScript library for building user interfaces with reusable components. Uses virtual DOM for performance and one-way data flow. Features component-based architecture, works with Redux for state management and React Native for mobile. Popular for its clarity, speed, and ecosystem.', '{"links": ["https://roadmap.sh/react", "https://www.youtube.com/watch?v=Bvwq_S0n2pk", "https://react.dev"]}'::jsonb),
    (74, 'Frontend', NULL, NULL, 'React', 'Next.js', NULL, 'Next.js is a React framework supporting server-side rendering and static site generation. Features automatic code splitting, file-based routing, CSS support, API routes, and optimized performance. Includes live updates, smart preloading, and easy deployment. Ideal for SEO-friendly applications.', '{"links": ["https://roadmap.sh/nextjs", "https://nextjs.org/", "https://youtu.be/1WmNXEVia8I"]}'::jsonb),
    (75, 'Frontend', NULL, NULL, 'React', 'Astro', NULL, 'Astro is a static site generator supporting multiple frameworks (React, Vue, Svelte) with partial hydration. Renders components to static HTML, sending JavaScript only when needed. Features file-based routing and markdown support. Ideal for blogs, documentation, and marketing sites.', '{"links": ["https://www.youtube.com/watch?v=e-hTm5VmofI", "https://astro.build/", "https://www.contentful.com/blog/what-is-astro/"]}'::jsonb),
    (76, 'Frontend', NULL, NULL, 'React', 'react-router', NULL, 'React Router enables client-side routing in React applications, creating single-page apps with multiple views. Handles URL management, provides route definition components, and supports lazy loading and route guards. The standard navigation solution for React applications.', '{"links": ["https://reactrouter.com/en/main", "https://hygraph.com/blog/routing-in-react", "https://www.youtube.com/watch?v=oTIJunBa6MA"]}'::jsonb),
    (77, 'Frontend', NULL, NULL, 'React', 'Tanstack Start', NULL, 'Tanstack Start is a full-stack framework built on React that simplifies the process of creating web applications with server-side rendering (SSR). It provides tools and conventions for routing, data fetching, and deployment, allowing developers to focus on building features rather than configuring infrastructure. It aims to streamline the development workflow for React-based SSR applications.', '{"links": ["https://tanstack.com/start/latest", "https://tanstack.com/start/latest/docs/framework/react/overview", "https://tanstack.com/start/latest/docs/framework/react/getting-started"]}'::jsonb),
    (78, 'Frontend', NULL, NULL, 'SSR', 'Angular', NULL, 'Angular is a popular tool from Google for building websites and web apps. It uses TypeScript (a type of JavaScript) to create large, efficient single-page applications (SPAs), where content loads in one go without needing to reload the whole page. Angular builds UIs with reusable components, like building blocks. It has features like two-way data binding (data updates automatically in different places), dependency injection (helps manage code parts), and a strong template system. Angular also offers tools for testing, page navigation, and managing app data, making it great for big, complex projects.', '{"links": ["https://roadmap.sh/angular", "https://angular.dev/tutorials/learn-angular", "https://www.youtube.com/watch?v=3qBXWUpoPHo"]}'::jsonb),
    (79, 'Frontend', NULL, NULL, 'SSR', 'Vue.js', NULL, 'Vue.js is a progressive JavaScript framework for building user interfaces. Features template syntax, virtual DOM, and component-based architecture. Easy to learn and incrementally adoptable. Works well with ecosystem tools for routing and state management. Known for flexibility, performance, and gentle learning curve.', '{"links": ["https://vuejs.org/", "https://thenewstack.io/meet-vue-js-flexible-javascript-framework/", "https://www.youtube.com/watch?v=VeNfHj6MhgA"]}'::jsonb),
    (80, 'Frontend', NULL, NULL, 'Vue.js', 'Nuxt.js', NULL, 'Nuxt.js is a Vue.js framework providing structure, automatic routing, and server-side rendering. Supports static site generation, code splitting, and data fetching. Offers flexible rendering options with focus on developer experience and performance. Popular for SEO-friendly Vue applications with plugin ecosystem.', '{"links": ["https://vueschool.io/courses/nuxtjs-fundamentals", "https://nuxtjs.org/", "https://explorers.netlify.com/learn/get-started-with-nuxt"]}'::jsonb),
    (81, 'Frontend', NULL, NULL, 'SSR', 'Svelte Kit', NULL, 'SvelteKit is a full-stack framework for building websites and applications with Svelte. Features file-based routing, code splitting, server-side rendering, and static site generation. Designed for simplicity and performance with excellent developer experience and easy deployment options.', '{"links": ["https://kit.svelte.dev/", "https://kit.svelte.dev/docs/introduction", "https://www.youtube.com/watch?v=H1eEFfAkIik"]}'::jsonb),
    (82, 'Frontend', NULL, NULL, 'Svelte Kit', 'Svelte', NULL, 'Svelte is a compile-time JavaScript framework building UIs with minimal runtime overhead. Compiles components to optimized vanilla JavaScript without virtual DOM. Features simple syntax, built-in state management, styling, and animations. Known for small bundle sizes and fast performance.', '{"links": ["https://www.youtube.com/playlist?list=PL4cUxeGkcC9hlbrVO_2QFVqVPhlZmz7tO", "https://svelte.dev/", "https://thenewstack.io/all-about-svelte-the-much-loved-state-driven-web-framework/"]}'::jsonb),
    (83, 'Frontend', NULL, NULL, NULL, 'SSG', 23, 'Static Site Generators (SSGs) build websites as pre-generated HTML files from content and templates. Make sites fast, secure, and easy to host. Examples: Jekyll, Hugo, Eleventy. Ideal for blogs, documentation, and content-focused sites with excellent performance.', '{"links": ["https://www.cloudflare.com/learning/performance/static-site-generator/", "https://thenewstack.io/get-back-basics-static-website-generators/", "https://www.youtube.com/watch?v=Qms4k6y7OgI"]}'::jsonb),
    (84, 'Frontend', NULL, NULL, 'SSG', 'Astro', NULL, 'Astro is a static site generator supporting multiple frameworks (React, Vue, Svelte) with partial hydration. Renders components to static HTML, sending JavaScript only when needed. Features file-based routing and markdown support. Ideal for blogs, documentation, and marketing sites.', '{"links": ["https://www.youtube.com/watch?v=e-hTm5VmofI", "https://astro.build/", "https://docs.astro.build/en/getting-started/"]}'::jsonb),
    (85, 'Frontend', NULL, NULL, 'SSG', 'Next.js', NULL, 'Next.js is a React framework supporting server-side rendering and static site generation. Features automatic code splitting, file-based routing, CSS support, API routes, and optimized performance. Includes live updates, smart preloading, and easy deployment. Ideal for SEO-friendly applications.', '{"links": ["https://nextjs.org/", "https://roadmap.sh/nextjs", "https://youtu.be/1WmNXEVia8I"]}'::jsonb),
    (86, 'Frontend', NULL, NULL, 'SSG', 'Vuepress', NULL, 'VuePress is a Vue.js-powered static site generator optimized for documentation. Creates fast, SEO-friendly sites with Vue-based theming, syntax highlighting, and Markdown support with Vue components. Features built-in search, responsive layouts, and plugin/theme customization. Ideal for documentation and simple websites.', '{"links": ["https://vuepress.vuejs.org/", "https://www.youtube.com/watch?v=iRhRdY7SQJg", "https://app.daily.dev/tags/vuejs?ref=roadmapsh"]}'::jsonb),
    (87, 'Frontend', NULL, NULL, 'SSG', 'Eleventy', NULL, 'Eleventy (11ty) is a flexible static site generator supporting multiple template languages (HTML, Markdown, JavaScript). Creates pages from data sources, adds no client-side JavaScript for fast loading. Highly customizable with useful plugins for navigation and image processing.', '{"links": ["https://www.11ty.dev/", "https://11ty.rocks/", "https://www.youtube.com/watch?v=-dM6AmNmMFA"]}'::jsonb),
    (88, 'Frontend', NULL, NULL, 'SSG', 'Nuxt.js', NULL, 'Nuxt.js is a Vue.js framework providing structure, automatic routing, and server-side rendering. Supports static site generation, code splitting, and data fetching. Offers flexible rendering options with focus on developer experience and performance. Popular for SEO-friendly Vue applications with plugin ecosystem.', '{"links": ["https://vueschool.io/courses/nuxtjs-fundamentals", "https://nuxtjs.org/", "https://explorers.netlify.com/learn/get-started-with-nuxt"]}'::jsonb),
    (89, 'Frontend', NULL, NULL, NULL, 'Type Checkers', 24, 'Type checkers are tools that analyze code to verify that the types of values used in a program are consistent with their declared or inferred types. They help catch type-related errors during development, before the code is run, by identifying mismatches between expected and actual data types. This process ensures that operations are performed on compatible data, reducing the likelihood of runtime errors and improving code reliability.', '{"links": ["https://finchtrade.com/glossary/type-checking"]}'::jsonb),
    (90, 'Frontend', NULL, NULL, NULL, 'Deployment', 25, 'Deployment is the process of making a website or web application available for users to access on the internet. It involves taking the code, assets (like images and fonts), and configuration files and placing them on a server or hosting platform. This process often includes steps like bundling the code, optimizing assets for performance, and configuring the server to properly serve the application.', '{"links": ["https://medium.com/devjavu/a-beginners-guide-to-web-deployment-b4ce704fe097", "https://hackernoon.com/deploying-frontend-applications-the-fun-way-bc3f69e15331", "https://strapi.io/blog/top-platforms-for-frontend-projects"]}'::jsonb),
    (91, 'Frontend', NULL, NULL, 'Deployment', 'GitHub Pages', NULL, 'GitHub Pages is a free static site hosting service that takes HTML, CSS, and JavaScript files directly from a GitHub repository and publishes them as a website. It''s ideal for hosting project documentation, portfolios, blogs, and other static websites. Pages supports custom domains, HTTPS, and Jekyll for automatic site generation. Each repository can have one project site, while user and organization accounts get one primary site at [username.github.io](http://username.github.io).', '{"links": ["http://username.github.io", "https://docs.github.com/en/pages", "https://docs.github.com/en/pages/quickstart"]}'::jsonb),
    (92, 'Frontend', NULL, NULL, 'Deployment', 'Vercel', NULL, 'Vercel is a platform designed for deploying and hosting web applications, particularly those built with modern frontend frameworks and static site generators. It provides features like automatic deployments from Git repositories, serverless functions, and a global content delivery network (CDN) to ensure fast and reliable performance. Vercel simplifies the process of taking a frontend project from development to production.', '{"links": ["https://vercel.com/docs", "https://vercel.com/docs/getting-started-with-vercel", "https://www.youtube.com/watch?v=Vx5nPGdsFaU"]}'::jsonb),
    (93, 'Frontend', NULL, NULL, 'Deployment', 'Cloudflare', NULL, 'Cloudflare is a service that sits between your website and its visitors, acting as a reverse proxy. It provides a range of features including a content delivery network (CDN) to speed up website loading times by caching content closer to users, DDoS protection to safeguard against malicious attacks, and SSL/TLS encryption to secure data transmission. It essentially helps improve website performance, security, and reliability.', '{"links": ["https://roadmap.sh/cloudflare", "https://www.cloudflare.com/en-gb/", "https://developers.cloudflare.com/pages/get-started/"]}'::jsonb),
    (94, 'Frontend', NULL, NULL, 'Deployment', 'Railway', NULL, 'Railway is a cloud platform that simplifies deploying web applications and services. It allows developers to deploy directly from their Git repositories, automatically handling infrastructure concerns like server provisioning, networking, and scaling. It supports various languages and frameworks, making it a versatile option for deploying frontend projects.', '{"links": ["https://railway.com/", "https://docs.railway.com/quick-start", "https://www.youtube.com/watch?v=JQIKobOcQ9k"]}'::jsonb),
    (95, 'Frontend', NULL, NULL, 'Deployment', 'Netlify', NULL, 'Netlify is a web development platform that simplifies building, deploying, and hosting websites and web applications. It automates the process of deploying static sites and single-page applications by directly connecting to your Git repository. When changes are pushed to the repository, Netlify automatically builds and deploys the updated version of your site. It also offers features like continuous deployment, serverless functions, and a global CDN for improved performance.', '{"links": ["https://www.netlify.com/", "https://docs.netlify.com/", "https://docs.netlify.com/start/get-started-guide/"]}'::jsonb),
    (96, 'Frontend', NULL, NULL, 'Deployment', 'Render', NULL, 'Render is a unified cloud platform that simplifies the process of deploying and hosting web applications, static websites, and backend services. It automates infrastructure management, allowing developers to focus on writing code rather than configuring servers. Render supports various programming languages and frameworks, offering features like automatic scaling, continuous deployment, and SSL certificates.', '{"links": ["https://render.com/", "https://render.com/docs", "https://thenewstack.io/render-cloud-deployment-with-less-engineering/"]}'::jsonb),
    (97, 'Frontend', NULL, NULL, NULL, 'Design Systems', 26, 'A design system is a structured collection of reusable components, guidelines, standards, and best practices that ensure consistency across an application''s visual design and user experience. It typically includes typography, colors, spacing, icons, UI components, interaction patterns, and documentation on how to use everything correctly.', '{"links": ["https://roadmap.sh/design-system", "https://www.figma.com/blog/design-systems-101-what-is-a-design-system/", "https://www.nngroup.com/articles/design-systems-101/"]}'::jsonb),
    (98, 'Frontend', NULL, NULL, NULL, 'Performance', 27, 'Performance, in the context of web development, refers to how quickly and efficiently a website or web application loads and responds to user interactions. It encompasses various aspects like loading times, rendering speed, and overall responsiveness. Optimizing performance ensures a smooth and enjoyable user experience, leading to increased engagement and satisfaction.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/Performance", "https://www.shopify.com/enterprise/blog/web-performance-optimization", "https://www.youtube.com/watch?v=0fONene3OIA"]}'::jsonb),
    (99, 'Frontend', NULL, NULL, 'Performance', 'DevTools Usage', NULL, 'DevTools are a set of web developer tools built directly into web browsers. They allow you to inspect and debug HTML, CSS, and JavaScript, monitor network activity, analyze performance bottlenecks, and more. By using DevTools, frontend developers can understand how their code is executed in the browser and identify areas for optimization.', '{"links": ["https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Tools_and_setup/What_are_browser_developer_tools", "https://aws.amazon.com/what-is/developer-tools/", "https://developer.chrome.com/docs/devtools"]}'::jsonb),
    (100, 'Frontend', NULL, NULL, 'Performance', 'Lighthouse', NULL, 'Lighthouse is an open-source, automated tool for improving the quality of web pages. You can run it against any web page, public or requiring authentication. It has audits for performance, accessibility, progressive web apps, SEO, and more. Lighthouse provides reports with actionable insights to help developers improve their website''s user experience.', '{"links": ["https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=es&pli=1", "https://developer.chrome.com/docs/lighthouse/overview", "https://github.com/GoogleChrome/lighthouse"]}'::jsonb),
    (101, 'Frontend', NULL, NULL, 'Performance', 'Service Workers', NULL, 'Service Workers are JavaScript files that act as proxy servers between web browsers and web servers. They can intercept network requests, cache resources, and deliver push notifications, even when the user is offline. This allows for improved performance and offline capabilities for web applications.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API", "https://web.dev/learn/pwa/service-workers", "https://developer.chrome.com/docs/workbox/service-worker-overview"]}'::jsonb),
    (102, 'Frontend', NULL, NULL, 'Performance', 'Streamed Responses', NULL, 'Streamed responses involve sending data from a server to a client in chunks, rather than waiting for the entire response to be ready before sending anything. This allows the browser to start processing and rendering content sooner, improving perceived performance and user experience, especially for large datasets or long-running processes. Instead of a single, large download, the data arrives incrementally.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/API/Streams_API", "https://platform.openai.com/docs/guides/streaming-responses", "https://dev.to/pranshu_kabra_fe98a73547a/streaming-responses-in-ai-how-ai-outputs-are-generated-in-real-time-18kb"]}'::jsonb),
    (103, 'Frontend', NULL, NULL, 'Performance', 'Cache-Control', NULL, 'Cache-Control is an HTTP header used to specify caching directives in HTTP requests and responses. These directives control how browsers and other intermediaries (like CDNs) should cache content. By setting appropriate Cache-Control headers, developers can influence whether a resource is stored, for how long, and under what conditions, ultimately impacting website loading speed and reducing server load.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control", "https://www.cloudflare.com/en-gb/learning/cdn/glossary/what-is-cache-control/", "https://www.youtube.com/watch?v=8TBWJo094yA"]}'::jsonb),
    (104, 'Frontend', NULL, NULL, NULL, 'Web Components', 28, 'Web Components create reusable HTML elements using Custom Elements, Shadow DOM, and HTML Templates. Work across browsers and frameworks with encapsulated styles and structure. Enable modular, shareable code with reduced style conflicts. Standard for building interoperable web parts.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/Web_Components", "https://webcomponents.github.io/", "https://www.youtube.com/watch?v=PCWaFLy3VUo"]}'::jsonb),
    (105, 'Frontend', NULL, NULL, 'Web Components', 'HTML Templates', NULL, 'The `<template>` HTML element holds hidden content for later use by JavaScript. Acts as a reusable blueprint for creating dynamic page elements. Enables efficient content templating and component-based development patterns in web applications.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots", "https://app.daily.dev/tags/html?ref=roadmapsh"]}'::jsonb),
    (106, 'Frontend', NULL, NULL, 'Web Components', 'Custom Elements', NULL, 'Custom Elements enable creating your own HTML tags as part of Web Components. Build reusable webpage components with custom behavior instead of nested standard HTML. Keeps HTML cleaner and components more manageable with encapsulated functionality.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements", "https://www.youtube.com/watch?v=1GT35DSdZbI", "https://app.daily.dev/tags/webdev?ref=roadmapsh"]}'::jsonb),
    (107, 'Frontend', NULL, NULL, 'Web Components', 'Shadow DOM', NULL, 'Shadow DOM creates private, encapsulated DOM trees inside elements, isolating HTML, CSS, and JavaScript from the main page. Prevents style and script conflicts, enabling cleaner, reusable components. Essential for web components requiring self-contained functionality.', '{"links": ["https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM", "https://youtu.be/7Tok22qxPzQ?si=2cw36PNSgFTcNHWx", "https://app.daily.dev/tags/dom?ref=roadmapsh"]}'::jsonb),
    (108, 'Frontend', NULL, NULL, NULL, 'GraphQL', 29, 'GraphQL is Facebook''s query language for APIs allowing clients to request exactly the data needed. Reduces over-fetching and under-fetching compared to REST. Ideal for mobile applications, complex APIs, and rapidly changing requirements with strong typing.', '{"links": ["https://roadmap.sh/graphql", "https://graphql.org/learn/", "https://thenewstack.io/introduction-to-graphql/"]}'::jsonb),
    (109, 'Frontend', NULL, NULL, 'GraphQL', 'Apollo', NULL, 'Apollo GraphQL is a comprehensive platform for GraphQL applications. Apollo Client handles caching, data fetching, and state management. Apollo Server builds GraphQL APIs. Includes tools for schema management, performance monitoring, and developer tooling for faster, scalable apps.', '{"links": ["https://roadmap.sh/graphql", "https://www.apollographql.com", "https://www.apollographql.com/docs/"]}'::jsonb),
    (110, 'Frontend', NULL, NULL, 'GraphQL', 'Relay Modern', NULL, 'Relay is Facebook''s JavaScript library for data-heavy React applications using GraphQL. Co-locates data requirements with components, enabling efficient fetching and updates. Handles caching, real-time updates, and optimistic UI changes. Ideal for complex applications requiring sophisticated data management.', '{"links": ["https://relay.dev/", "https://github.com/facebook/relay", "https://www.youtube.com/watch?v=A4POd93GI_I"]}'::jsonb),
    (111, 'Frontend', NULL, NULL, NULL, 'Accessibility', 30, 'Website accessibility ensures sites are usable by everyone, including people with disabilities. Involves alt text for images, keyboard navigation, color contrast, and captions. Benefits all users, supports legal compliance, and expands audience reach.', '{"links": ["https://web.dev/accessibility", "https://youtube.com/playlist?list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g"]}'::jsonb),
    (112, 'Frontend', NULL, NULL, NULL, 'PWAs', 31, 'Progressive Web Apps (PWAs) are web applications behaving like native apps using HTML, CSS, JavaScript. Feature offline functionality, push notifications, home screen installation, and service workers for caching. Cross-platform, discoverable, and cost-effective alternative to native apps.', '{"links": ["https://web.dev/learn/pwa/", "https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/", "https://www.youtube.com/watch?v=3ODP6tTpjqA"]}'::jsonb),
    (113, 'Frontend', NULL, NULL, NULL, 'Mobile Apps', 32, 'Visit the following resources to learn more:', '{"links": ["https://reactnative.dev/", "https://flutter.dev", "https://ionicframework.com"]}'::jsonb),
    (114, 'Frontend', NULL, NULL, 'Mobile Apps', 'React Native', NULL, 'React Native enables building native mobile apps for iOS and Android using JavaScript and React. Compiles to native components for authentic look and performance. Features code sharing, hot reloading, and device API access. Ideal for React developers transitioning to mobile development.', '{"links": ["https://roadmap.sh/react-native", "https://reactnative.dev/", "https://app.daily.dev/tags/react?ref=roadmapsh"]}'::jsonb),
    (115, 'Frontend', NULL, NULL, 'Mobile Apps', 'Flutter', NULL, 'Flutter is Google''s cross-platform framework building apps for iOS, Android, web, desktop from single Dart codebase. Features rich widget library, hot reload, and custom rendering engine for consistent UI. Popular for mobile development, expanding to web and desktop platforms.', '{"links": ["https://roadmap.sh/flutter", "https://www.youtube.com/watch?v=VPvVD8t02U8", "https://flutter.dev"]}'::jsonb),
    (116, 'Frontend', NULL, NULL, 'Mobile Apps', 'Ionic', NULL, 'Ionic is an open-source mobile toolkit that allows developers to build high-quality cross-platform applications for iOS, Android, and the web using a single codebase. It leverages web technologies like HTML, CSS, and JavaScript, and integrates seamlessly with popular frameworks such as Angular, React, and Vue. By providing a rich library of pre-designed UI components and native mobile features, it enables the creation of performant, native-feeling apps without needing to write platform-specific code for every device.', '{"links": ["https://ionicframework.com/docs", "https://www.youtube.com/watch?v=5Gj4Y8zvl-s&list=PLlyAM-8-I7S9iNcZRfP4SQJhm4Mw5q5ku"]}'::jsonb),
    (117, 'Frontend', NULL, NULL, NULL, 'Desktop Apps', 33, 'JavaScript builds desktop apps using Electron, NW.js, or Tauri for cross-platform development (Windows, Mac, Linux). Electron powers VS Code and Discord. Provides file system access and native integration. Trade-offs: faster development vs. performance and resource usage compared to native apps.', '{"links": ["https://www.electronjs.org/", "https://nwjs.io/", "https://tauri.app/"]}'::jsonb),
    (118, 'Frontend', NULL, NULL, 'Desktop Apps', 'Electron', NULL, 'Electron builds cross-platform desktop apps using web technologies (HTML, CSS, JavaScript) with Chromium and Node.js. Provides native OS access and powers apps like VS Code. Enables rapid development but can be resource-intensive. Popular choice for web developers.', '{"links": ["https://www.electronjs.org/", "https://www.electronjs.org/docs/latest/", "https://www.youtube.com/watch?v=ML743nrkMHw"]}'::jsonb),
    (119, 'Frontend', NULL, NULL, 'Desktop Apps', 'Tauri', NULL, 'Tauri builds small, secure desktop apps using web technologies with Rust backend. Uses system webview instead of bundled browser, resulting in smaller apps. Features strong security and JavaScript framework compatibility. Focuses on performance and minimal resource usage compared to Electron.', '{"links": ["https://tauri.app/", "https://tauri.app/v1/guides/", "https://thenewstack.io/how-tauri-turns-web-designs-into-compact-native-apps/"]}'::jsonb),
    (120, 'Frontend', NULL, NULL, 'Desktop Apps', 'Flutter', NULL, 'Flutter is Google''s cross-platform framework building apps for iOS, Android, web, desktop from single Dart codebase. Features rich widget library, hot reload, and custom rendering engine for consistent UI. Popular for mobile development, expanding to web and desktop platforms.', '{"links": ["https://roadmap.sh/flutter", "https://www.youtube.com/watch?v=VPvVD8t02U8", "https://flutter.dev"]}'::jsonb);

-- Make sure career rows exist before inserting nodes.
INSERT INTO career_roles (career_name)
SELECT DISTINCT seed.career_name
FROM roadmap_skill_node_seed seed
WHERE NOT EXISTS (
    SELECT 1 FROM career_roles career
    WHERE career.career_name = seed.career_name
);

-- Insert nodes first. Self-references are resolved in the next UPDATE.
INSERT INTO skill_nodes (node_id, career_id, subtree_name, node_name, level, description, resource)
SELECT
    seed.node_id,
    career.career_id,
    seed.subtree_name,
    seed.node_name,
    seed.level,
    seed.description,
    seed.resource
FROM roadmap_skill_node_seed seed
JOIN career_roles career ON career.career_name = seed.career_name
WHERE NOT EXISTS (
    SELECT 1
    FROM skill_nodes existing
    WHERE existing.career_id = career.career_id
      AND existing.node_name = seed.node_name
      AND COALESCE(existing.subtree_name, '') = COALESCE(seed.subtree_name, '')
      AND COALESCE(existing.level, -1) = COALESCE(seed.level, -1)
);

-- Resolve connect_to and child_node_of by node name inside the same roadmap/career.
-- If duplicate node names exist, the first row in the CSV is used as the referenced node.
WITH inserted_nodes AS (
    SELECT seed.row_no, seed.node_id, seed.career_name, seed.connect_to_name, seed.child_node_of_name
    FROM roadmap_skill_node_seed seed
), reference_nodes AS (
    SELECT DISTINCT ON (seed.career_name, seed.node_name)
        seed.career_name,
        seed.node_name,
        seed.node_id
    FROM roadmap_skill_node_seed seed
    ORDER BY seed.career_name, seed.node_name, seed.row_no
)
UPDATE skill_nodes node
SET
    connect_to = connect_node.node_id,
    child_node_of = parent_node.node_id
FROM inserted_nodes seed
LEFT JOIN reference_nodes connect_node
    ON connect_node.career_name = seed.career_name
   AND connect_node.node_name = seed.connect_to_name
LEFT JOIN reference_nodes parent_node
    ON parent_node.career_name = seed.career_name
   AND parent_node.node_name = seed.child_node_of_name
WHERE node.node_id = seed.node_id;

COMMIT;
