server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000        # 10 min
      max-lifetime: 1800000       # 30 min
      connection-timeout: 30000   # 30s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # milliseconds
